name: Run SendMatchList 🟢

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    env:
      DOTNET_VERSION: '8.0.x'
      PROJECT_PATH: './AutomationTennis/AutomationTennis.csproj'
      PUBLISH_DIR: './publish'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }}

      - name: Update Slack Configuration
        run: |
          echo "Atualizando WebhookUrlChannelWTA no appsettings.json"
          sed -i 's|"WebhookUrlChannelWTA": ".*"|"WebhookUrlChannelWTA": "${{ secrets.SLACK_WEBHOOK_URL }}"|g' ${{ env.PUBLISH_DIR }}/appsettings.json

      - name: Run Method SendMatchListOfDayToSlackChannelWTA
        run: dotnet ${{ env.PUBLISH_DIR }}/AutomationTennis.dll SendMatchListOfDayToSlackChannelWTA
