name: Publish Project and Commit 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - master  # ajuste conforme sua branch

jobs:
  publish-and-commit:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'
      PROJECT_PATH: './AutomationTennis/AutomationTennis.csproj'
      PUBLISH_DIR: './publish'
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }}

      - name: Update Slack Webhook URL in appsettings.json
        run: |
          echo "Atualizando WebhookUrlChannelWTA no appsettings.json"
          sed -i 's|"WebhookUrlChannelWTA": ".*"|"WebhookUrlChannelWTA": "'"${SLACK_WEBHOOK_URL}"'"|g' ${{ env.PUBLISH_DIR }}/appsettings.json

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push published files
        run: |
          git add ${{ env.PUBLISH_DIR }}
          git diff --cached --quiet || (git commit -m "Atualiza publish automático [skip ci]" && git push)
